CREATE DATABASE newdatabase;
USE newdatabase;

DROP TABLE IF EXISTS STUDENT;


CREATE TABLE STUDENT (
    stdid INT(5), 
    stdname VARCHAR(20), 
    dob DATE, 
    doj DATE, 
    fee INT(5), 
    gender CHAR
);


DESC STUDENT;


INSERT INTO STUDENT (stdid, stdname, dob, doj, fee, gender)
VALUES (1, 'SHAREEF', '2001-01-10', '2001-10-05', 10000, 'M');

INSERT INTO STUDENT (stdid, stdname, dob, doj, fee, gender)
VALUES (2, 'NADEEM', '2019-11-03', '2001-10-26', 11000, 'M');


ALTER TABLE STUDENT ADD PHONE_NO BIGINT;


ALTER TABLE STUDENT CHANGE COLUMN PHONE_NO STUDENT_NO BIGINT;


ALTER TABLE STUDENT RENAME TO STUDENINFO;


SELECT * FROM STUDENINFO;


ALTER TABLE STUDENINFO DROP COLUMN gender;


DELETE FROM STUDENINFO WHERE stdid = 2;


UPDATE STUDENINFO
SET STUDENT_NO = 1234567890
WHERE stdid = 1;


SELECT * FROM STUDENINFO;