use department;

SELECT E1.ENAME AS ManagerName
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.EMPNO = E2.MGR_NO
GROUP BY E1.ENAME
HAVING COUNT(E2.EMPNO) = (
    SELECT MAX(EmployeeCount)
    FROM (
        SELECT COUNT(E3.EMPNO) AS EmployeeCount
        FROM EMPLOYEE E3
        WHERE E3.MGR_NO IS NOT NULL
        GROUP BY E3.MGR_NO
    ) AS Counts
);

SELECT M.ENAME AS ManagerName
FROM EMPLOYEE M
JOIN EMPLOYEE E ON M.EMPNO = E.MGR_NO
GROUP BY M.EMPNO, M.ENAME, M.SAL
HAVING M.SAL > AVG(E.SAL);

SELECT D.DNAME, E.ENAME, E.SAL
FROM EMPLOYEE E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE (
    SELECT COUNT(DISTINCT E2.SAL)
    FROM EMPLOYEE E2
    WHERE E2.DEPTNO = E.DEPTNO AND E2.SAL > E.SAL
) = 1;

SELECT *
FROM INCENTIVES I
JOIN EMPLOYEE E ON I.EMPNO = E.EMPNO
WHERE I.INCENTIVE_DATE BETWEEN '2019-01-01' AND '2019-01-31'
AND I.INCENTIVE_AMOUNT = (
    SELECT MAX(INCENTIVE_AMOUNT)
    FROM INCENTIVES
    WHERE INCENTIVE_DATE BETWEEN '2019-01-01' AND '2019-01-31'
    AND INCENTIVE_AMOUNT < (
        SELECT MAX(INCENTIVE_AMOUNT)
        FROM INCENTIVES
        WHERE INCENTIVE_DATE BETWEEN '2019-01-01' AND '2019-01-31'
    )
);

SELECT E.ENAME AS EmployeeName, M.ENAME AS ManagerName, D.DNAME AS Department
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.MGR_NO = M.EMPNO
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO = M.DEPTNO;
